# Generated by Django 4.0.5 on 2022-11-16 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callbacks', '0002_alter_callback_options_alter_callback_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callback',
            options={'verbose_name': 'callback', 'verbose_name_plural': 'callbacks'},
        ),
        migrations.AlterField(
            model_name='callback',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='callback',
            name='description',
            field=models.TextField(blank=True, max_length=256, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='callback',
            name='fullname',
            field=models.CharField(max_length=120, verbose_name='fullname'),
        ),
        migrations.AlterField(
            model_name='callback',
            name='phone_number',
            field=models.CharField(max_length=120, verbose_name='phone_number'),
        ),
        migrations.AlterField(
            model_name='callback',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='updated'),
        ),
    ]
