# Generated by Django 4.0.4 on 2022-06-11 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=256, null=True, verbose_name='url')),
                ('first_number', models.CharField(max_length=256, null=True, verbose_name='first_number')),
                ('second_number', models.CharField(max_length=256, null=True, verbose_name='second_number')),
                ('working_time', models.CharField(max_length=256, null=True, verbose_name='working_time')),
                ('address', models.TextField(max_length=256, null=True, verbose_name='address')),
                ('map_x', models.FloatField(null=True, verbose_name='map_x')),
                ('map_y', models.FloatField(null=True, verbose_name='map_y')),
                ('map_zoom', models.IntegerField(null=True, verbose_name='map_zoom')),
                ('yandex_metrika', models.TextField(null=True, verbose_name='yandex_metrika')),
            ],
            options={
                'verbose_name': 'settings',
                'verbose_name_plural': 'settings',
            },
        ),
    ]
