# Generated by Django 4.0.4 on 2022-06-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_rename_x_point_map_x_rename_y_point_map_y'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='yandex_metrika',
            field=models.CharField(max_length=128, null=True, verbose_name='yandex_metrika'),
        ),
    ]
