# Generated by Django 4.0.5 on 2022-06-23 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_alter_settings_yandex_metrika'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='point',
            options={'verbose_name': 'Точка', 'verbose_name_plural': 'Точки'},
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'Настройки', 'verbose_name_plural': 'Настройки'},
        ),
        migrations.AlterField(
            model_name='point',
            name='map_x',
            field=models.FloatField(null=True, verbose_name='X'),
        ),
        migrations.AlterField(
            model_name='point',
            name='map_y',
            field=models.FloatField(null=True, verbose_name='Y'),
        ),
        migrations.AlterField(
            model_name='point',
            name='settings',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='points', to='settings.settings', verbose_name='Настройки'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='address',
            field=models.TextField(max_length=256, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='email',
            field=models.CharField(max_length=256, null=True, verbose_name='Адрес электронной почты'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='first_number',
            field=models.CharField(max_length=256, null=True, verbose_name='Первый номер телефона'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='map_x',
            field=models.FloatField(null=True, verbose_name='X'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='map_y',
            field=models.FloatField(null=True, verbose_name='Y'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='map_zoom',
            field=models.IntegerField(null=True, verbose_name='Приблежение'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='second_number',
            field=models.CharField(max_length=256, null=True, verbose_name='Второй номер телефона'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='url',
            field=models.URLField(max_length=256, null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='working_time',
            field=models.CharField(max_length=256, null=True, verbose_name='Рабочее время'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='yandex_metrika',
            field=models.CharField(max_length=128, null=True, verbose_name='Яндекс Метрика'),
        ),
    ]
