# Generated by Django 4.0.5 on 2022-11-16 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_alter_point_options_alter_settings_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='point',
            options={'verbose_name': 'point', 'verbose_name_plural': 'points'},
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'settings', 'verbose_name_plural': 'settings'},
        ),
        migrations.AddField(
            model_name='settings',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banners', verbose_name='banner'),
        ),
        migrations.AlterField(
            model_name='point',
            name='map_x',
            field=models.FloatField(null=True, verbose_name='map_x'),
        ),
        migrations.AlterField(
            model_name='point',
            name='map_y',
            field=models.FloatField(null=True, verbose_name='map_y'),
        ),
        migrations.AlterField(
            model_name='point',
            name='settings',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='points', to='settings.settings', verbose_name='settings'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='address',
            field=models.TextField(max_length=256, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='email',
            field=models.CharField(max_length=256, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='first_number',
            field=models.CharField(max_length=256, null=True, verbose_name='first_number'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='map_x',
            field=models.FloatField(null=True, verbose_name='map_x'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='map_y',
            field=models.FloatField(null=True, verbose_name='map_y'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='map_zoom',
            field=models.IntegerField(null=True, verbose_name='map_zoom'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='second_number',
            field=models.CharField(max_length=256, null=True, verbose_name='second_number'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='url',
            field=models.URLField(max_length=256, null=True, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='working_time',
            field=models.CharField(max_length=256, null=True, verbose_name='working_time'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='yandex_metrika',
            field=models.CharField(max_length=128, null=True, verbose_name='yandex_metrika'),
        ),
    ]
